In [87]:
import numpy as np

class Mancala:
    def __init__(self, holes=7, stones=7, board=None):
        self.n_holes = holes
        self.n_stones = stones
        self.north_store = self.n_holes
        self.south_store = self.n_holes * 2 + 1
        self.board = board
        if self.board is None:
            self.reset()
    
    def reset(self):
        self.board = np.full((self.n_holes+1) * 2, self.n_stones)
        self.board[self.n_holes] = 0
        self.board[-1] = 0
    
    def step(self, side, hole):
        pos = self._get_board_pos(side, hole)
        stones = self.board[pos]
        self.board[pos] = 0
        pos += 1
        last_position = 0
        while stones > 0:
            if not self.is_opponent_store(side, pos):
                self.board[pos] += 1
                stones -= 1
                if stones == 0:
                    last_pos = pos
            pos = (pos + 1) % len(self.board)
        if self.is_self_store(side, last_pos):
            return "{}:continue".format(side)
        if self.is_self_hole(side, last_pos) and self.board[last_pos] == 1 \
            and self.board[self.get_opponent_pos(last_pos)] != 0:
            scores_stored = self.get_self_store(side)
            self.board[scores_stored] = self.board[scores_stored]+ self.board[last_pos] \
                + self.board[self.get_opponent_pos(last_pos)]
            self.board[last_pos] = 0
            self.board[self.get_opponent_pos(last_pos)] = 0
        return self.get_opponent_side(side)
    
    
    
            
    def get_self_store(self,side):
        if side == 'south':
            return self.south_store
        else:
            return self.north_store
    def get_opponent_side(self,side):
        if side == 'north':
            return 'south'
        else:
            return 'north'
    
    def is_self_hole(self, side, pos):
        return side == 'south' and self.north_store < pos < self.south_store \
            or side == 'north' and pos < self.south_store
    
    def get_opponent_pos(self, pos):
        return 2 * self.n_holes - pos
        
    def is_self_store(self,side, pos):
        return side == 'south' and pos == self.south_store \
            or side == 'north' and pos == self.north_store
    
    
    def is_opponent_store(self, side, pos):
        return side == 'south' and pos == self.north_store \
            or side == 'north' and pos == self.south_store
        
    def _get_board_pos(self, side, hole):
        return hole - 1 if side == 'north' else hole + self.n_holes
    
    def __str__(self):
        formatter = {'int': lambda x: f'{x: >3d}'}
        return '{:2d}  {}\n    {}  {}'.format(
            self.board[self.north_store],
            np.array2string(self.board[0:self.north_store][::-1], formatter=formatter),
            np.array2string(self.board[self.north_store+1:self.south_store], formatter=formatter),
            self.board[self.south_store]
        )

# game = Mancala()
# game.step('south', 1)
# print(game)
# game.step('south', 2)
# print(game)
# game.step('north', 2)
# print(game)
game = Mancala()
print(game.step('south', 1))
print(game)
#print(game.board)
print(game.step('north', 1))
print(game)
print(game.step('south', 2))
print(game)
print(game.step('north', 2))
print(game)
print(game.step('south', 2))
print(game)
print(game.step('north', 1))
print(game)

print(game.step('south', 1))
print(game)

south:continue
 0  [  7   7   7   7   7   7   7]
    [  0   8   8   8   8   8   8]  1
north:continue
 1  [  8   8   8   8   8   8   0]
    [  0   8   8   8   8   8   8]  1
north
 1  [  8   8   8   8   8   9   1]
    [  0   0   9   9   9   9   9]  2
south
 2  [  9   9   9   9   9   0   1]
    [  1   1  10   9   9   9   9]  2
north
 2  [  9   9   9   9   9   0   1]
    [  1   0  11   9   9   9   9]  2
south
12  [  9   9   9   9   9   0   0]
    [  1   0  11   9   9   0   9]  2
north
12  [  9   0   9   9   9   0   0]
    [  0   0  11   9   9   0   9]  12
